@startditaa -E
Debug Port Packet           (528 Bytes)
+---------------------------------------+
| Debug Port Packet Header  (12 Bytes)  |
| +-----------------------------------+ |
| | -Framing Signature       -4 Bytes | |
| +-----------------------------------+ |
| | -Payload Size Info       -4 Bytes | |
| +-----------------------------------+ |
| | -Packet Type             -1 Byte  | |
| +-----------------------------------+ |
| | -Reserve                 -3 Bytes | |
| +-----------------------------------+ |
+---------------------------------------+
| Debug Packet Payload      (512 Bytes) |
+---------------------------------------+
| Checksum                  (4 Bytes)   |
+---------------------------------------+
@endditaa
