@startditaa -E
Debug Port Packet           (528 Bytes)
+---------------------------------------+
| Debug Port Packet Header  (16 Bytes)  |
| +-----------------------------------+ |
| | -Framing Signature       -4 Bytes | |
| +-----------------------------------+ |
| | -Debug Packet CHecksum   -4 Bytes | |
| +-----------------------------------+ |
| | -Payload Size Info       -4 Bytes | |
| +-----------------------------------+ |
| | -Packet Type             -1 Byte  | |
| +-----------------------------------+ |
| | -Reserve                 -1 Bytes | |
| +-----------------------------------+ |
| | -Packet Header Checksum  -2 Bytes | |
| +-----------------------------------+ |
+---------------------------------------+
| Debug Packet Payload      (512 Bytes) |
+---------------------------------------+
@endditaa
