@startuml
file "Common Command File"
node "CEF" {
  [Main]--> [Communication] : Output
  [Communication]--> [Main] : Request
  [Common Command File] <..> [Main]
}
node "Python Test Utilities" {
  [User Debug] --> [Communication] : Command
  [Communication]-->[User Debug] : Response/Logging
  [User Debug] <..> [Common Command File]
}

@enduml
